name: Run job in a container
on:
  push:
    branches:
      main
jobs:
  job-in-container:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: echo node version
        run: node --version

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
